#! /bin/bash

function _g_completions() {
    G_CONF="${BASH_SOURCE%/*}/yml/g.yml"
    source ${BASH_SOURCE%/*}/sh/conf.sh
    local cur prev commands projects topics

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    commands=("help" "new" "rm" "ls")
    projects=($(g_get_projects))
    declare -A topic_actions=(
        ["issue"]="new ls edit close reopen"
        ["issues"]="new ls edit close reopen"
        ["i"]="new ls edit close reopen"
        ["label"]="new ls edit rm"
        ["labels"]="new ls edit rm"
        ["pr"]="new ls close reopen merge"
        ["mr"]="new ls close reopen merge"
    )
    topics=(${!topic_actions[@]})

    case "$COMP_CWORD" in
        1)
            COMPREPLY=( $(compgen -W "${commands[*]} ${projects[*]}" -- "$cur") )
            ;;
        2)
            if [[ " ${projects[*]} " =~ " ${COMP_WORDS[1]} " ]]; then
                # Complete the second argument with topics
                COMPREPLY=( $(compgen -W "${topics[*]}" -- "$cur") )
            fi
            ;;
        3)
            if [[ -n "${topic_actions[${COMP_WORDS[2]}]}" ]]; then
                COMPREPLY=( $(compgen -W "${topic_actions[${COMP_WORDS[2]}]}" -- "$cur") )
            fi
            ;;
    esac
}

complete -F _g_completions g
