# ANSI COLORS
local RED_="\033[31m"
local GREEN_="\033[32m"
local YELLOW_="\033[33m"
local BLUE_="\033[34m"
local MAGENTA_="\033[35m"

COLOR_PRIMARY=${COMMA_THEME_COLOR_PRIMARY:-$BLUE_}
COLOR_SECONDARY=${COMMA_THEME_COLOR_SECONDARY:-$MAGENTA_}
COLOR_ERROR=${COMMA_THEME_COLOR_ERROR:-$RED_}
COLOR_DONE=${COMMA_THEME_COLOR_DONE:-$GREEN_}
COLOR_INFO=${COMMA_THEME_COLOR_INFO:-$MAGENTA_}
COLOR_WARN=${COMMA_THEME_COLOR_WARN:-$YELLOW_}
COLOR_DEBUG=${COMMA_THEME_COLOR_DEBUG:-$YELLOW_}
COLOR_ENTRY=${COMMA_THEME_COLOR_ENTRY:-$BLUE_}
COLOR_LINE=${COMMA_THEME_COLOR_LINE:-$BLUE_}
COLOR_DOUBLE_LINE=${COMMA_THEME_COLOR_DOUBLE_LINE:-$BLUE_}
COLOR_RESET="\033[0m"

# TEXT STRUCTURE
TEXT_ERROR=${COMMA_THEME_TEXT_ERROR:-error}
TEXT_DONE=${COMMA_THEME_TEXT_DONE:-done}
TEXT_INFO=${COMMA_THEME_TEXT_INFO:-info}
TEXT_WARN=${COMMA_THEME_TEXT_WARN:-warn}
TEXT_DEBUG=${COMMA_THEME_TEXT_DEBUG:-DEBUG}
local TEXT_LINE_="-----------------------"
TEXT_LINE=${COMMA_THEME_TEXT_LINE:-$TEXT_LINE_}
local TEXT_DOUBLE_LINE_="========================"
TEXT_DOUBLE_LINE=${COMMA_THEME_TEXT_DOUBLE_LINE:-$TEXT_DOUBLE_LINE_}

WIDTH_TEXT=${COMMA_THEME_WIDTH_TEXT:-80}
WIDTH_ENTRY=${COMMA_THEME_WIDTH_ENTRY:-12}
local FZF_GEOMETRY_="--height=30% --layout=reverse"
FZF_GEOMETRY="${COMMA_THEME_FZF:-$FZF_GEOMETRY_}"
